apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-general
spec:
  provider:
    vault:
      server: "https://vault.local.m1xxos.tech"
      path: "general"
      version: "v2"
      auth:
        appRole:
          path: "cluster-general"
          roleRef:
            name: "vault-rid"
            namespace: "external-secrets"
            key: "rid"
          secretRef:
            name: "my-secret"
            namespace: "secret-admin"
            key: "vault-role-id"
