apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-general
spec:
  provider:
    vault:
      server: "https://vault.local.m1xxos.tech"
      path: "general"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets"
          key: "token"
