---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-clustermesh
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-general
    kind: ClusterSecretStore
  target:
    name: cilium-clustermesh
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ${CILIUM_REMOTE_CLUSTER}: |
          endpoints:
          - https://clustermesh-apiserver.kube-system.svc:2379
          trusted-ca-file: /var/lib/cilium/clustermesh/local-etcd-client-ca.crt
          key-file: /var/lib/cilium/clustermesh/local-etcd-client.key
          cert-file: /var/lib/cilium/clustermesh/local-etcd-client.crt
  data:
  - secretKey: _remote_cluster_name
    remoteRef:
      key: clustermesh/${CILIUM_REMOTE_CLUSTER}
      property: ${CILIUM_REMOTE_CLUSTER}
