---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-kvstoremesh
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-general
    kind: ClusterSecretStore
  target:
    name: cilium-kvstoremesh
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: clustermesh/${CILIUM_REMOTE_CLUSTER}
