apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-configs
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-system
  interval: 10m0s
  path: ./clusters/main-configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
