---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- volume-snapshotter/crd.yaml
- volume-snapshotter/controller.yaml
- cert-manager/cert-issuer.yaml
- cert-manager/certificate.yaml
- external-secrets/vault-store.yaml
- external-secrets/cf-token.yaml
- external-secrets/dhi-secret.yaml
- cilium/push-secret.yaml
