---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-ns.yaml
- external-secrets-ns.yaml
- flux.yaml
- lh-ns.yaml
- role.yaml
- traefik-ns.yaml
- vault-rid.yaml
- vault-sid.yaml
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml
