apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-m1xxos-tech
  namespace: traefik
spec:
  secretName: local-m1xxos-tech
  dnsNames:
  - "${DNS_NAME}"
  - "*.${DNS_NAME}"
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
